# Code generated by protoc-gen-elixir. DO NOT EDIT.
defmodule Acme.Chat.V1.ChatService.Service do
  use GRPC.Service, name: "acme.chat.v1.ChatService", protoc_gen_elixir_version: "0.12.0"

  rpc(:Send, Acme.Chat.V1.SendRequest, Acme.Chat.V1.SendResponse)
end
