// Code generated by MockGen. DO NOT EDIT.
// テスト用のモック。実体のクライアントへ委譲するので呼び出し元として検出されるが、
// 「この API を誰が呼んでいるか」を読むうえではノイズになる
package mocks

import (
	"context"

	apb "github.example.com/org/client-lib/a/v1"
)

type MockAServiceClient struct {
	inner apb.AServiceClient
}

func (m *MockAServiceClient) GetA(ctx context.Context, in *apb.GetAReq) (*apb.GetARes, error) {
	return m.inner.GetA(ctx, in)
}
