// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: chain/b/v1/b.proto

package bv1

import (
	context "context"
	grpc "google.golang.org/grpc"
)

const BService_GetB_FullMethodName = "/chain.b.v1.BService/GetB"

type GetBReq struct{ Id string }
type GetBRes struct{ V string }

type BServiceClient interface {
	GetB(ctx context.Context, in *GetBReq, opts ...grpc.CallOption) (*GetBRes, error)
}

func NewBServiceClient(cc grpc.ClientConnInterface) BServiceClient { return nil }

type BServiceServer interface {
	GetB(context.Context, *GetBReq) (*GetBRes, error)
}

type UnimplementedBServiceServer struct{}
