// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: acme/foo/v1/foo.proto

package foov1

import (
	context "context"
	grpc "google.golang.org/grpc"
)

const (
	FooService_GetFoo_FullMethodName = "/acme.foo.v1.FooService/GetFoo"
)

type GetFooReq struct{ Id string }
type GetFooRes struct{ Title string }

type FooServiceClient interface {
	GetFoo(ctx context.Context, in *GetFooReq, opts ...grpc.CallOption) (*GetFooRes, error)
}

func NewFooServiceClient(cc grpc.ClientConnInterface) FooServiceClient { return nil }

type FooServiceServer interface {
	GetFoo(context.Context, *GetFooReq) (*GetFooRes, error)
}

type UnimplementedFooServiceServer struct{}

const BarService_Ping_FullMethodName = "/acme.foo.v1.BarService/Ping"

type PingReq struct{ Id string }
type PingRes struct{ Ok string }

type BarServiceClient interface {
	Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingRes, error)
}

func NewBarServiceClient(cc grpc.ClientConnInterface) BarServiceClient { return nil }

type BarServiceServer interface {
	Ping(context.Context, *PingReq) (*PingRes, error)
}

type UnimplementedBarServiceServer struct{}
