// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: chain/a/v1/a.proto

package av1

import (
	context "context"
	grpc "google.golang.org/grpc"
)

const AService_GetA_FullMethodName = "/chain.a.v1.AService/GetA"

type GetAReq struct{ Id string }
type GetARes struct{ V string }

type AServiceClient interface {
	GetA(ctx context.Context, in *GetAReq, opts ...grpc.CallOption) (*GetARes, error)
}

func NewAServiceClient(cc grpc.ClientConnInterface) AServiceClient { return nil }

type AServiceServer interface {
	GetA(context.Context, *GetAReq) (*GetARes, error)
}

type UnimplementedAServiceServer struct{}
