// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file acme/chat/v1/chat.proto (package acme.chat.v1, syntax proto3)
/* eslint-disable */

import { SendRequest, SendResponse } from "./chat_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service acme.chat.v1.ChatService
 */
export const ChatService = {
  typeName: "acme.chat.v1.ChatService",
  methods: {
    send: {
      name: "Send",
      I: SendRequest,
      O: SendResponse,
      kind: MethodKind.Unary,
    },
  },
} as const;
