// 生成スタブ(protoc 系ジェネレータの出力)を、置き場所ではなく中身の署名で同定する。
//
// 生成物のパス規約は組織ごとに違い、別リポジトリで配布されていることも多い。
// そこでパスを一切前提にせず、protoc が言語を問わず必ず埋め込む
// フルメソッド名("/user.v1.UserService/GetUser")を署名として使う。
// これがあるファイルは「proto から生成されたクライアント/サーバスタブ」で、
// そこから元 proto の package・service・RPC 名を復元できる。
//
// グラフ本体の走査(scan.ts の walk)は gen / generated / vendor を除外するが、
// 生成物はまさにそこに置かれるため、この探索は独自に歩く(読むのは署名だけ)。

import * as fs from 'node:fs';
import * as path from 'node:path';
import { isExcluded, type Config } from './context.ts';
import { matchesAnyGlob } from './path-glob.ts';

/** 巨大な生成物を丸ごと読まないための上限(署名はファイル先頭側に集中する)。 */
const READ_LIMIT = 512 * 1024;

// 走査から外すディレクトリ。gen / generated / vendor は「外さない」のがこの探索の要点。
const SKIP = new Set([
  '.git', 'node_modules', '.cache', 'coverage', '__pycache__', '.idea', '.vscode', '_build', 'deps',
]);

// 生成スタブの可能性があるファイル名(言語横断)。ここは足切りで、確定は中身の署名で行う。
const STUB_FILE =
  /(\.pb\.(go|ex)|_pb2(_grpc)?\.py|_pb\.(d\.ts|ts|js)|_connect\.(ts|js)|_grpc(_web)?_pb\.(ts|js)|\.pb\.(ts|js))$/;

// ジェネレータが出すヘッダ。ファイル名規約から外れた生成物を拾うための第 2 の足切り。
const GENERATED_HEADER =
  /(Code generated by protoc|@generated by protoc|GENERATED CODE -- DO NOT EDIT|Generated by the protocol buffer compiler|@generated from file)/;

// 構成非依存の署名。"/user.v1.UserService/GetUser" は多くの生成コードに現れる。
const FULL_METHOD = /["'`]\/((?:[A-Za-z_]\w*\.)*)([A-Za-z_]\w*)\/([A-Za-z_]\w*)["'`]/g;

// フルメソッド名を出さないジェネレータ(connect-es / protobuf-es / protoc-gen-elixir)向けの第 2 の署名。
// service の完全修飾名と RPC 名が別々に書かれるので、両方を拾って組み立てる。
const SERVICE_TYPE_NAME = /(?:typeName|name)\s*:\s*["']((?:[A-Za-z_]\w*\.)+)([A-Za-z_]\w*)["']/g;
const TS_METHOD_NAME = /\bname:\s*["']([A-Za-z_]\w*)["']/g;
const EX_RPC_NAME = /\brpc\s*\(?\s*:([A-Za-z_]\w*)/g;

// 元 proto のパス。protoc-gen-go は "source:"、connect-es は "@generated from file" を出す。
const SOURCE_COMMENT = /(?:source|@generated from file):\s*(\S+\.proto)/;

/** 生成物が宣言する RPC 1 件。package を落とすと別 API と取り違えるので必ず保持する。 */
export interface ArtifactMethod {
  pkg: string; // proto の package 名(例 "acme.user.v1")。空になることもある
  service: string; // 例 "UserService"
  method: string; // 例 "GetUser"
}

/** 1 ディレクトリ = 1 生成パッケージとして束ねた生成物。 */
export interface GeneratedArtifact {
  id: string; // ノード id('artifact:' + dir)
  dir: string; // ws 相対ディレクトリ
  files: string[]; // ws 相対
  protoPath?: string; // source コメントから得た .proto パス
  methods: ArtifactMethod[];
}

/** 完全修飾の RPC 名。package が取れないときは短名にフォールバックする。 */
export function fullRpcName(m: ArtifactMethod): string {
  return (m.pkg === '' ? '' : m.pkg + '.') + m.service + '.' + m.method;
}

/** この生成物が宣言する service 名(短名)の集合。 */
export function servicesOf(artifact: GeneratedArtifact): Set<string> {
  return new Set(artifact.methods.map((m) => m.service));
}

export function artifactNodeId(dir: string): string {
  return 'artifact:' + dir;
}

function readHead(abs: string): string | undefined {
  try {
    const stat = fs.statSync(abs);
    if (!stat.isFile()) return undefined;
    if (stat.size <= READ_LIMIT) return fs.readFileSync(abs, 'utf8');
    const fd = fs.openSync(abs, 'r');
    try {
      const buf = Buffer.alloc(READ_LIMIT);
      const read = fs.readSync(fd, buf, 0, READ_LIMIT, 0);
      return buf.subarray(0, read).toString('utf8');
    } finally {
      fs.closeSync(fd);
    }
  } catch {
    return undefined;
  }
}

/** 候補ファイルを集める(名前の足切りのみ。中身の判定は呼び出し側)。 */
function collectCandidates(rootAbs: string, config: Config): string[] {
  const out: string[] = [];
  const extra = config.indirection?.artifactPaths ?? [];
  // artifactPaths に名前が出てくるディレクトリは、既定の除外より設定を優先して降りる
  const forced = new Set(extra.flatMap((p) => p.split('/').filter((seg) => seg !== '' && !seg.includes('*'))));
  const visit = (dirAbs: string, rel: string): void => {
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(dirAbs, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      const childRel = rel === '' ? entry.name : rel + '/' + entry.name;
      if (isExcluded(childRel, config, entry.isDirectory())) continue;
      if (entry.isDirectory()) {
        if (SKIP.has(entry.name) && !forced.has(entry.name)) continue;
        visit(path.join(dirAbs, entry.name), childRel);
      } else if (entry.isFile() && (STUB_FILE.test(entry.name) || matchesAnyGlob(childRel, extra))) {
        out.push(childRel);
      }
    }
  };
  visit(rootAbs, '');
  return out.sort();
}

/** service の完全修飾名と RPC 名が分かれて書かれる生成物から署名を組み立てる。 */
function readSplitSignature(src: string): ArtifactMethod[] {
  SERVICE_TYPE_NAME.lastIndex = 0;
  const service = SERVICE_TYPE_NAME.exec(src);
  if (!service) return [];
  const pkg = service[1].replace(/\.$/, '');
  const names = new Set<string>();
  for (const re of [TS_METHOD_NAME, EX_RPC_NAME]) {
    re.lastIndex = 0;
    for (let m = re.exec(src); m; m = re.exec(src)) names.add(m[1]);
  }
  return [...names].map((method) => ({ pkg, service: service[2], method }));
}

/** 生成物 1 ファイルから署名を読む。生成物でなければ undefined。 */
function readSignature(src: string): { protoPath?: string; methods: ArtifactMethod[] } | undefined {
  const methods: ArtifactMethod[] = [];
  FULL_METHOD.lastIndex = 0;
  for (let m = FULL_METHOD.exec(src); m; m = FULL_METHOD.exec(src)) {
    methods.push({ pkg: m[1].replace(/\.$/, ''), service: m[2], method: m[3] });
  }
  const generated = GENERATED_HEADER.test(src);
  // 署名も生成ヘッダも無ければ生成物と見なさない(手書きコードを巻き込まない)
  if (methods.length === 0 && !generated) return undefined;
  if (methods.length === 0) methods.push(...readSplitSignature(src));
  const sm = SOURCE_COMMENT.exec(src);
  return { ...(sm ? { protoPath: sm[1] } : {}), methods };
}

/** ワークスペース内の生成スタブをディレクトリ単位に束ねて返す。 */
export function discoverGeneratedArtifacts(rootAbs: string, config: Config): GeneratedArtifact[] {
  const byDir = new Map<string, GeneratedArtifact>();
  for (const rel of collectCandidates(rootAbs, config)) {
    const src = readHead(path.join(rootAbs, rel));
    if (src === undefined) continue;
    const sig = readSignature(src);
    if (!sig) continue;
    const dir = path.posix.dirname(rel);
    let artifact = byDir.get(dir);
    if (!artifact) {
      artifact = { id: artifactNodeId(dir), dir, files: [], methods: [] };
      byDir.set(dir, artifact);
    }
    artifact.files.push(rel);
    if (sig.protoPath !== undefined && artifact.protoPath === undefined) artifact.protoPath = sig.protoPath;
    const seen = new Set(artifact.methods.map(fullRpcName));
    for (const m of sig.methods) {
      if (seen.has(fullRpcName(m))) continue;
      seen.add(fullRpcName(m));
      artifact.methods.push(m);
    }
  }
  // RPC を 1 つも復元できなかったディレクトリは、間接層の中継点として使えないので落とす
  return [...byDir.values()].filter((a) => a.methods.length > 0).sort((a, b) => (a.dir < b.dir ? -1 : 1));
}

// テスト用に個別関数も公開
export { readSignature };
