# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc


class ChatServiceStub(object):
    """チャット。"""

    def __init__(self, channel):
        self.Send = channel.unary_unary(
            '/acme.chat.v1.ChatService/Send',
        )
